server {                                                                                                                                                                 
      listen 80;                                                                                                                                                                   
      server_name localhost;                                                                                                                                                      
      charset utf-8;                                                                                                                                                               
                  
      # Requêtes vers l'API → transmises à PHP-FPM (Laravel)
      location ~ ^/(api|sanctum) {
          fastcgi_pass app:9000;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
          include fastcgi_params;
          fastcgi_param REQUEST_URI $request_uri;
      }

      # images uploadées
      location ^~ /storage/ {
          alias /var/www/html/storage/app/public/;
      }


      # Tout le reste → fichiers statiques du frontend
      location / {
          root /var/www/frontend;
          try_files $uri $uri/ /index.html;
      }
  }